### PR TITLE
fix(#905): Polish the Trace view of the camel plugin

### LINKED ISSUE #905: CamelPlugin: Broken Trace view
Trace view definitely needs some care: 
Screenshot 2024-04-25 at 08 17 30

### PR DESCRIPTION
**Pull request by mmelko**
fixes #905

Screenshot 2024-04-26 at 13 09 43
Screenshot 2024-04-26 at 13 09 28

### CODE REVIEW

File: packages/hawtio/src/plugins/camel/trace/Trace.tsx [hunk 1]
```diff
@@ -199,84 +189,85 @@ export const Trace: React.FunctionComponent = () => {
...
-                  </RouteDiagramContext.Provider>
-                </PanelMainBody>
-              </PanelMain>
-            </Panel>
-
+      <PanelMain>
+        <PanelMainBody>
+          {!isTracing && (
+            <React.Fragment>
+              <Text className='noTracing' data-testid='no-tracing' component='p'>
```
Comment (phantomjinx) [inline packages/hawtio/src/plugins/camel/trace/Trace.tsx:196]: Are not the data-testid attributes supposed to have unique values? The 3 <Text> components here have the same id.

**Review by phantomjinx — COMMENTED** [review]
I think this looks okay but am not sure the screenshots help to clarify the changes. Are you able to do a quick before/after video?

**Comment by phantomjinx** [comment]
The drawer (?) with the message header pairs table says '46305' at the top. Is that the message ID? If it is, maybe needs an Id: label or something as it seems to be floating on its own?

**Review by tadayosi — APPROVED** [review]
