### PR TITLE
fix(#369):Fixes watches to modify attributes to watch correctly

### LINKED ISSUE #369: Chart - Edit watches not removing charts
Putting it here for traceability.

Peek 2023-06-20 10-59

I think the problem lies in one of the later fixes I did to ensure that children keys were not being duplicated but it seems I didn't test it thoroughly. I'll submit a fix shortly

### PR DESCRIPTION
**Pull request by joshiraez**
Fixes #369 

Peek 2023-06-20 11-40

### CODE REVIEW

File: packages/hawtio/src/plugins/shared/chart/WatchableAttributesForm.tsx [hunk 1]
```diff
@@ -67,17 +73,19 @@ export const WatchableAttributesForm = ({
...
-              newWatches[newUnwatchedAttribute.id] = {
-                ...(newWatches[newUnwatchedAttribute.id] || {}),
-                ...Object.fromEntries(newUnwatchedAttribute.children?.map(({ id }) => [id, false]) || []),
+              newWatches[newUnwatchedAttribute.text] = {
+                ...(newWatches[newUnwatchedAttribute.text] || {}),
+                ...Object.fromEntries(newUnwatchedAttribute.children?.map(({ text }) => [text, false]) || []),
               }
             })
 
+            console.log(newWatches)
```
Comment (tadayosi) [inline packages/hawtio/src/plugins/shared/chart/WatchableAttributesForm.tsx:87]: don't leave `console.log`. if you want to leave some debug logging, use `log.debug` from `globals.ts`

**Review by tadayosi — CHANGES_REQUESTED** [review]

File: packages/hawtio/src/plugins/shared/chart/WatchableAttributesForm.tsx (hunk 1 above)
Comment (joshiraez) [reply packages/hawtio/src/plugins/shared/chart/WatchableAttributesForm.tsx:87]: So sorry. Removing this right away.

I'm going to build a custom lint rule at this rate so it tells me of any console.logs. It happens too much
